using Microsoft.VisualStudio.TestTools.UnitTesting;
using Metodi;

namespace Test
{
    [TestClass]
    public class BioinformaticaTest
    {
        [TestMethod]
        public void TestLunghezza()
        {
            int file1 = BioinformaticaMetodi.Lunghezza("sensibile.txt");
            int file2 = BioinformaticaMetodi.Lunghezza("resistente.txt");
            int risposta1 = 3901;
            int risposta2 = 3901;
            Assert.AreEqual(risposta1, file1);
            Assert.AreEqual(risposta2, file2);
        }

        [DataTestMethod]
        [DataRow("sensibile.txt", "resistente.txt", 3901, 3901)]
        public void DataTestLunghezza(string file1, string file2, int risposta1, int risposta2)
        {
            int lunghezza1 = BioinformaticaMetodi.Lunghezza(file1);
            int lunghezza2 = BioinformaticaMetodi.Lunghezza(file2);
            Assert.AreEqual(risposta1, lunghezza1);
            Assert.AreEqual(risposta2, lunghezza2);
        }

        [TestMethod]
        public void TestPosizioneErrore()
        {
            int posizione = BioinformaticaMetodi.PosizioneErrore("sensibile.txt", "resistente.txt");
            int aspettato = 1603;
            Assert.AreEqual(aspettato, posizione);
        }

        [DataTestMethod]
        [DataRow("sensibile.txt", "resistente.txt", 1603)]
        public void DataTestPosizioneErrata(string file1, string file2, int aspettato)
        {
            int posizione = BioinformaticaMetodi.PosizioneErrore(file1, file2);
            Assert.AreEqual(aspettato, posizione);
        }

        [TestMethod]
        public void TestDNAidentico()
        {
            string identico = BioinformaticaMetodi.DNAidentico("sensibile.txt", "resistente.txt");
            string aspettato = "CGGGTATTTGAGGAATGCGCCGTCCTGCGCTATTGTTGGACGTTGCGCTGGCTACTTCCTGCCCACCTCACCCGCCACTTGACACCGTGGTCTTAGTCTGAGCCCAGTTTGCGGCTCAGCGGTTTAGTTGCGTGCGTGAGATCCGGACAGATCGTTCGCCGGCCGAAACCGACAAAATTATCGCGGTTGACAGGCCCGTGGGCACCGCTCCTATAATGGCTCTCGTTGGTCGCATGAAGTGCAGGAGGGATGCATCTTGGCAGATTCCCGCCAGAGCAAAACAGCCGCTAGTCCTAGTCCGAGTCGCCCGCAAAGTTCCTCGAATAACTCCGTACCCGGAGCGCCAAACCGGGTCTCCTTCGCTAAGCTGCGCGAACCACTTGAGGTTCCGGGACTCCTTGACGTCCAGACCGATTCGTTCGAGTGGCTGATCGGTTCGCCGCGCTGGCGCGAATCCGCCGCCGAGCGGGGTGATGTCAACCCAGTGGGTGGCCTGGAAGAGGTGCTCTACGAGCTGTCTCCGATCGAGGACTTCTCCGGGTCGATGTCGTTGTCGTTCTCTGACCCTCGTTTCGACGATGTCAAGGCACCCGTCGACGAGTGCAAAGACAAGGACATGACGTACGCGGCTCCACTGTTCGTCACCGCCGAGTTCATCAACAACAACACCGGTGAGATCAAGAGTCAGACGGTGTTCATGGGTGACTTCCCGATGATGACCGAGAAGGGCACGTTCATCATCAACGGGACCGAGCGTGTGGTGGTCAGCCAGCTGGTGCGGTCGCCCGGGGTGTACTTCGACGAGACCATTGACAAGTCCACCGACAAGACGCTGCACAGCGTCAAGGTGATCCCGAGCCGCGGCGCGTGGCTCGAGTTTGACGTCGACAAGCGCGACACCGTCGGCGTGCGCATCGACCGCAAACGCCGGCAACCGGTCACCGTGCTGCTCAAGGCGCTGGGCTGGACCAGCGAGCAGATTGTCGAGCGGTTCGGGTTCTCCGAGATCATGCGATCGACGCTGGAGAAGGACAACACCGTCGGCACCGACGAGGCGCTGTTGGACATCTACCGCAAGCTGCGTCCGGGCGAGCCCCCGACCAAAGAGTCAGCGCAGACGCTGTTGGAAAACTTGTTCTTCAAGGAGAAGCGCTACGACCTGGCCCGCGTCGGTCGCTATAAGGTCAACAAGAAGCTCGGGCTGCATGTCGGCGAGCCCATCACGTCGTCGACGCTGACCGAAGAAGACGTCGTGGCCACCATCGAATATCTGGTCCGCTTGCACGAGGGTCAGACCACGATGACCGTTCCGGGCGGCGTCGAGGTGCCGGTGGAAACCGACGACATCGACCACTTCGGCAACCGCCGCCTGCGTACGGTCGGCGAGCTGATCCAAAACCAGATCCGGGTCGGCATGTCGCGGATGGAGCGGGTGGTCCGGGAGCGGATGACCACCCAGGACGTGGAGGCGATCACACCGCAGACGTTGATCAACATCCGGCCGGTGGTCGCCGCGATCAAGGAGTTCTTCGGCACCAGCCAGCTGAGCCAATTCATGGACCAGAACAACCCGCTGTCGGGGTTGACCCACAAGCGCCGACTG";
            Assert.AreEqual(aspettato, identico);
        }

        [DataTestMethod]
        [DataRow("sensibile.txt", "resistente.txt", "CGGGTATTTGAGGAATGCGCCGTCCTGCGCTATTGTTGGACGTTGCGCTGGCTACTTCCTGCCCACCTCACCCGCCACTTGACACCGTGGTCTTAGTCTGAGCCCAGTTTGCGGCTCAGCGGTTTAGTTGCGTGCGTGAGATCCGGACAGATCGTTCGCCGGCCGAAACCGACAAAATTATCGCGGTTGACAGGCCCGTGGGCACCGCTCCTATAATGGCTCTCGTTGGTCGCATGAAGTGCAGGAGGGATGCATCTTGGCAGATTCCCGCCAGAGCAAAACAGCCGCTAGTCCTAGTCCGAGTCGCCCGCAAAGTTCCTCGAATAACTCCGTACCCGGAGCGCCAAACCGGGTCTCCTTCGCTAAGCTGCGCGAACCACTTGAGGTTCCGGGACTCCTTGACGTCCAGACCGATTCGTTCGAGTGGCTGATCGGTTCGCCGCGCTGGCGCGAATCCGCCGCCGAGCGGGGTGATGTCAACCCAGTGGGTGGCCTGGAAGAGGTGCTCTACGAGCTGTCTCCGATCGAGGACTTCTCCGGGTCGATGTCGTTGTCGTTCTCTGACCCTCGTTTCGACGATGTCAAGGCACCCGTCGACGAGTGCAAAGACAAGGACATGACGTACGCGGCTCCACTGTTCGTCACCGCCGAGTTCATCAACAACAACACCGGTGAGATCAAGAGTCAGACGGTGTTCATGGGTGACTTCCCGATGATGACCGAGAAGGGCACGTTCATCATCAACGGGACCGAGCGTGTGGTGGTCAGCCAGCTGGTGCGGTCGCCCGGGGTGTACTTCGACGAGACCATTGACAAGTCCACCGACAAGACGCTGCACAGCGTCAAGGTGATCCCGAGCCGCGGCGCGTGGCTCGAGTTTGACGTCGACAAGCGCGACACCGTCGGCGTGCGCATCGACCGCAAACGCCGGCAACCGGTCACCGTGCTGCTCAAGGCGCTGGGCTGGACCAGCGAGCAGATTGTCGAGCGGTTCGGGTTCTCCGAGATCATGCGATCGACGCTGGAGAAGGACAACACCGTCGGCACCGACGAGGCGCTGTTGGACATCTACCGCAAGCTGCGTCCGGGCGAGCCCCCGACCAAAGAGTCAGCGCAGACGCTGTTGGAAAACTTGTTCTTCAAGGAGAAGCGCTACGACCTGGCCCGCGTCGGTCGCTATAAGGTCAACAAGAAGCTCGGGCTGCATGTCGGCGAGCCCATCACGTCGTCGACGCTGACCGAAGAAGACGTCGTGGCCACCATCGAATATCTGGTCCGCTTGCACGAGGGTCAGACCACGATGACCGTTCCGGGCGGCGTCGAGGTGCCGGTGGAAACCGACGACATCGACCACTTCGGCAACCGCCGCCTGCGTACGGTCGGCGAGCTGATCCAAAACCAGATCCGGGTCGGCATGTCGCGGATGGAGCGGGTGGTCCGGGAGCGGATGACCACCCAGGACGTGGAGGCGATCACACCGCAGACGTTGATCAACATCCGGCCGGTGGTCGCCGCGATCAAGGAGTTCTTCGGCACCAGCCAGCTGAGCCAATTCATGGACCAGAACAACCCGCTGTCGGGGTTGACCCACAAGCGCCGACTG")]
        public void DataTestDNAidentico(string file1, string file2, string aspettato)
        {
            string identico = BioinformaticaMetodi.DNAidentico(file1, file2);
            Assert.AreEqual(aspettato, identico);
        }

        [TestMethod]
        public void TestCaratteriDiversi()
        {
            int ndiversi = BioinformaticaMetodi.CaratteriDiversi("sensibile.txt", "resistente.txt");
            int aspettato = 1;
            Assert.AreEqual(aspettato, ndiversi);
        }

        [DataTestMethod]
        [DataRow("sensibile.txt", "resistente.txt", 1)]
        public void DataTestCaratteriDiversi(string file1, string file2, int aspettato)
        {
            int ndiversi = BioinformaticaMetodi.CaratteriDiversi(file1, file2);
            Assert.AreEqual(aspettato, ndiversi);
        }
    }
}
